# This workflow runs when a PR is requested
name: PR Validation
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: ['src/**', 'data/**', '.github/workflows/pr-validation.yml', 'package.json', 'pnpm.lock']

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    env:
      fork_pr: ${{ github.event.pull_request.head.repo.full_name != github.repository }}

    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout DCS
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Check formatting
        run: pnpm lint:prettier

      - name: Cache ESLint
        uses: actions/cache@v4
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('eslint.config.js') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Run ESLint
        run: pnpm lint-report:cached
        continue-on-error: true

      - name: Upload ESLint results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: eslint-results
          path: eslint.results.json
          retention-days: 1

      - name: Generate Data
        run: pnpm generate-data

      - name: porcelain check
        uses: dorny/paths-filter@v3
        id: data
        with:
          base: HEAD
          filters: |
            changed:
              - '**'

      - name: Commit other updated values
        if: steps.data.outputs.changed == 'true' && !env.fork_pr
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          commit_message: other updates from manifest
          commit_user_name: DIM Font Bot
          commit_user_email: destinyitemmanager@gmail.com
          commit_author: DIM Font Bot <destinyitemmanager@gmail.com>

      - name: Fail if data not generated
        if: steps.data.outputs.changed == 'true' && env.fork_pr
        uses: actions/github-script@v8
        with:
          script: |
            core.setFailed('Generated data is out of date. Please run `pnpm generate-data` and commit the changes.')
